{
 "title": "METEO",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Inside Values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Air Quality",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT aq FROM invalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
     "rawQueryText": "SELECT aq FROM invalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Heat Index",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT ith FROM invalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
     "rawQueryText": "SELECT ith FROM invalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT temperature FROM invalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
     "rawQueryText": "SELECT temperature FROM invalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT humidity FROM invalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
     "rawQueryText": "SELECT humidity FROM invalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT pressure FROM invalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
     "rawQueryText": "SELECT pressure FROM invalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT altitude FROM invalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
     "rawQueryText": "SELECT altitude FROM invalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Outside Values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT temperature FROM outvalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
       "rawQueryText": "SELECT temperature FROM outvalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT humidity FROM outvalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
       "rawQueryText": "SELECT humidity FROM outvalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Wind Speed",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT wind FROM outvalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
       "rawQueryText": "SELECT wind FROM outvalues ORDER BY datetime(\"date\") DESC LIMIT 1;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Inside Values  Historial",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Air Quality",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "queryText": "SELECT aq, strftime('%s', datetime(\"date\", 'localtime', '-4 hours')) AS time FROM invalues;\r\n",
       "rawQueryText": "SELECT aq, strftime('%s', datetime(\"date\", 'localtime', '-4 hours')) AS time FROM invalues;\r\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Heat Index",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "queryText": "SELECT ith, strftime('%s', datetime(\"date\", 'localtime', '-4 hours')) AS time FROM invalues;",
       "rawQueryText": "SELECT ith, strftime('%s', datetime(\"date\", 'localtime', '-4 hours')) AS time FROM invalues;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "queryText": "SELECT temperature, strftime('%s', datetime(\"date\", 'localtime', '-4 hours')) AS time FROM invalues;",
       "rawQueryText": "SELECT temperature, strftime('%s', datetime(\"date\", 'localtime', '-4 hours')) AS time FROM invalues;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "queryText": "SELECT humidity, strftime('%s', datetime(\"date\", 'localtime', '-4 hours')) AS time FROM invalues;",
       "rawQueryText": "SELECT humidity, strftime('%s', datetime(\"date\", 'localtime', '-4 hours')) AS time FROM invalues;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Outside Values Historial",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "queryText": "SELECT temperature, strftime('%s', datetime(\"date\", 'localtime', '-4 hours')) AS time FROM outvalues;",
       "rawQueryText": "SELECT temperature, strftime('%s', datetime(\"date\", 'localtime', '-4 hours')) AS time FROM outvalues;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "queryText": "SELECT humidity, strftime('%s', datetime(\"date\", 'localtime', '-4 hours')) AS time FROM outvalues;",
       "rawQueryText": "SELECT humidity, strftime('%s', datetime(\"date\", 'localtime', '-4 hours')) AS time FROM outvalues;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "Wind Speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "targets": [
      {
       "queryText": "SELECT wind, strftime('%s', datetime(\"date\", 'localtime', '-4 hours')) AS time FROM outvalues;",
       "rawQueryText": "SELECT wind, strftime('%s', datetime(\"date\", 'localtime', '-4 hours')) AS time FROM outvalues;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  }
 ]
}